ALTER TYPE "BaasBotStatus" ADD VALUE IF NOT EXISTS 'awaiting_reconciliation';
ALTER TYPE "BaasBotStatus" ADD VALUE IF NOT EXISTS 'recording_paused';
ALTER TYPE "BaasBotStatus" ADD VALUE IF NOT EXISTS 'api_request_stop';
ALTER TYPE "BaasBotStatus" ADD VALUE IF NOT EXISTS 'bot_removed';
ALTER TYPE "BaasBotStatus" ADD VALUE IF NOT EXISTS 'MEET_LOGIN_UNAVAILABLE';
ALTER TYPE "BaasBotStatus" ADD VALUE IF NOT EXISTS 'MEET_LOGIN_REQUIRED';
ALTER TYPE "BaasBotStatus" ADD VALUE IF NOT EXISTS 'MEET_LOGIN_FAILED_SAML_REJECTED';
ALTER TYPE "BaasBotStatus" ADD VALUE IF NOT EXISTS 'MEET_LOGIN_FAILED_TIMEOUT';

UPDATE meeting
SET "baasStatus" = 'MEET_LOGIN_UNAVAILABLE'
WHERE "baasStatus" = 'meet_login_error';
