const GOOGLE_CALENDAR_EVENTS_READONLY_SCOPE =
  'https://www.googleapis.com/auth/calendar.events.readonly'

const CALENDAR_SYNC_WINDOW_DAYS = 2

const PRIMARY_CALENDAR_ID = 'primary'

const CALENDAR_WEBHOOK_PATH = '/calendar/webhook'

export {
  CALENDAR_SYNC_WINDOW_DAYS,
  CALENDAR_WEBHOOK_PATH,
  GOOGLE_CALENDAR_EVENTS_READONLY_SCOPE,
  PRIMARY_CALENDAR_ID
}
